---
- hosts: localhost
  gather_facts: No
  
  tasks:
  - name: Clone front-end
    git:
      repo: 'https://github.com/marikifua/front-end.git'
      dest: /var/lib/jenkins/repositories/front-end

  - name: Docker Login
    docker_login:
      registry: https://gcr.io
      username: _json_key
      debug: true
      password: " {{ lookup('file', '~/credential/marikkey.json')}}"

  - name: build front-end
    docker_image:
      name: gcr.io/quantum-tracker-251814/front-end:3.0.0-{{ BUILD_NUMBER }}
      build:
        path: /var/lib/jenkins/repositories/front-end
      source: build
      push: yes

  - name: TAG front-end
    docker_image:
      name: gcr.io/quantum-tracker-251814/front-end:3.0.0-{{ BUILD_NUMBER }}
      repository: gcr.io/quantum-tracker-251814/front-end:latest
      force_tag: yes
      source: local
      push: yes

  - name: Remove image latest
    docker_image:
      state: absent
      name: gcr.io/quantum-tracker-251814/front-end
      tag: latest
  
  - name: Remove image version
    docker_image:
      state: absent
      name: gcr.io/quantum-tracker-251814/front-end
      tag: "3.0.0-{{ BUILD_NUMBER }}"
  
- hosts: app-tf

  tasks:

  - name: Create a network
    docker_network:
      name: my_net

  - name: Pull front-end image
    docker_image:
      name: gcr.io/quantum-tracker-251814/front-end
      source: pull 
  
  - name: Create front-end container
    docker_conainer:
      name: front-end
      image: gcr.io/quantum-tracker-251814/front-end
      network_mode: "my_net"  
      recreate: yes
      state: started  
      restart_policy: always
         