- name: build
  gather_facts: No
  hosts: localhost

  tasks:
  - name: Clone front-end
    git:
      repo: 'https://github.com/marikifua/front-end.git'
      dest: /var/lib/jenkins/repositories/front-end
#    become: yes
#    become_user: root
#    become_method: sudo

  - name: build front-end
    docker_image:
      name: gcr.io/quantum-tracker-251814/front-end
      build:
        path: /var/lib/jenkins/repositories/front-end
        pull: yes
      source: build
#    become: yes
#    become_user: root
#    become_method: sudo

         