---
- name: build
  gather_facts: No
  hosts: localhost

  tasks:
  - name: Clone front-end
    git:
      repo: 'https://github.com/marikifua/front-end.git'
      dest: /var/lib/jenkins/repositories/front-end

  - name: Docker Login
    docker_login:
      registry: https://gcr.io
      username: _json_key
      debug: true
      password: " {{ lookup('file', '~/credential/marikkey.json')}}"

  - name: build front-end
    docker_image:
      name: gcr.io/quantum-tracker-251814/front-end:0.0.3-{{ BUILD_NUMBER }}
      build:
        path: /var/lib/jenkins/repositories/front-end
      source: build
      push: yes

  - name: TAG front-end
    docker_image:
      name: gcr.io/quantum-tracker-251814/front-end:0.0.3-{{ BUILD_NUMBER }}
      repository: gcr.io/quantum-tracker-251814/front-end:latest
      force_tag: yes
      source: local
      push: yes

  - name: Remove image latest
    docker_image:
      state: absent
      name: gcr.io/quantum-tracker-251814/front-end
      tag: latest
  
  - name: Remove image version
    docker_image:
      state: absent
      name: gcr.io/quantum-tracker-251814/front-end
      tag: "0.0.3-{{ BUILD_NUMBER }}"
  

         