---
- name: build
  gather_facts: No
  hosts: localhost

  tasks:
  - name: Clone catalogue
    git:
      repo: 'https://github.com/marikifua/catalogue.git'
      dest: /var/lib/jenkins/repositories/catalogue

  - name: Docker Login
    docker_login:
      registry: https://gcr.io
      username: _json_key
      debug: true
      password: " {{ lookup('file', '~/credential/marikkey.json')}}"

  - name: build catalogue-db
    docker_image:
      name: gcr.io/quantum-tracker-251814/catalogue-db:3.0.0-{{ BUILD_NUMBER }}
      build:
        path: /var/lib/jenkins/repositories/catalogue/docker/catalogue-db
      source: build
      push: yes

  - name: TAG catalogue-db
    docker_image:
      name: gcr.io/quantum-tracker-251814/catalogue-db:3.0.0-{{ BUILD_NUMBER }}
      repository: gcr.io/quantum-tracker-251814/catalogue-db:latest
      force_tag: yes
      source: local
      push: yes

  - name: Remove image latest catalogue-db
    docker_image:
      state: absent
      name: gcr.io/quantum-tracker-251814/catalogue-db
      tag: latest
  
  - name: Remove image version catalogue-db
    docker_image:
      state: absent
      name: gcr.io/quantum-tracker-251814/catalogue-db
      tag: "3.0.0-{{ BUILD_NUMBER }}"

  - name: build catalogue
    docker_image:
      name: gcr.io/quantum-tracker-251814/catalogue:3.0.0-{{ BUILD_NUMBER }}
      build:
        path: /var/lib/jenkins/repositories/catalogue/docker/catalogue
      source: build
      push: yes

  - name: TAG catalogue
    docker_image:
      name: gcr.io/quantum-tracker-251814/catalogue:3.0.0-{{ BUILD_NUMBER }}
      repository: gcr.io/quantum-tracker-251814/catalogue:latest
      force_tag: yes
      source: local
      push: yes

  - name: Remove image latest catalogue
    docker_image:
      state: absent
      name: gcr.io/quantum-tracker-251814/catalogue
      tag: latest
  
  - name: Remove image version catalogue
    docker_image:
      state: absent
      name: gcr.io/quantum-tracker-251814/catalogue
      tag: "3.0.0-{{ BUILD_NUMBER }}"

         