---

- hosts: db-tf
  gather_facts: No

  tasks:
  - name: Create kibana container
    docker_container:
      name: kibana
      image: kibana:6.8.4
      network_mode: "my_net"
      ports:
        - "5601:5601"
      recreate: yes
      state: started 

  - name: Create ElasticSearch container
    docker_container:
      name: elasticsearch
      image: elasticsearch:6.8.4
      network_mode: "my_net"
      ports:
        - "9200:9200"
        - "9300:9300"
      env: 
        ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      recreate: yes
      state: started         

  - name: copy filebeat conf to db-tf
    copy:
      src: ./filebeat.yml
      dest: /tmp
      force: yes
    become: yes

  - name: Create filebeat container
    docker_container:
      name: filebeat
      image: docker.io/elastic/filebeat:6.8.4
      network_mode: "my_net"
      command: ["sh","-c","filebeat -e -strict.perms=false"]
      volumes:
        - /tmp/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
      env: 
        output.elasticsearch.hosts: "elasticsearch:9200"
      recreate: yes
      state: started      

      