filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: log
  paths:
    - /var/log/messages
  encoding: plain
  input_type: log
      
- type: docker
  combine_partial: true
  multiline.pattern: "^[[:space:]]+(at|\\.{3})\\b|^Caused by:"
  multiline.negate: false
  multiline.match: after
  containers:
    path: "/var/lib/docker/containers"
    stream: "all"
    ids:
      - "*"

processors:
- add_docker_metadata: ~
    #host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:db-tf:9200}'
  username: 'elastic'
  password: 'changeme'

logging.json: true
logging.metrics.enabled: false